### ISSUE TITLE
Error after app build.

### ISSUE THREAD

**Issue by xxanqw** [xxanqw/winrar-installer#1]
Extra strange error after app build
```Traceback (most recent call last):
  File "C:\Users\potik\Documents\winrar-installer\build\app.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\windows\__init__.py", line 1, in <module windows>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\windows\mainwindow.py", line 4, in <module windows.mainwindow>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\logic\__init__.py", line 2, in <module logic>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\logic\downloader.py", line 2, in <module logic.downloader>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\requests\__init__.py", line 164, in <module requests>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\requests\api.py", line 11, in <module requests.api>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\requests\sessions.py", line 15, in <module requests.sessions>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\potik\Documents\winrar-installer\build\requests\adapters.py", line 81, in <module requests.adapters>
FileNotFoundError: [Errno 2] No such file or directory
```

While app works fine from source code.

**Comment by xxanqw** [comment]
Will work soon on it
for now just use the 1.0.2 release (got bugs too..)

**Comment by xxanqw** [comment]
Not a bug.. Just a some sort of dismatch on latest Python no fix needed
